#!/usr/bin/env bash
# Function to display DNS information for a subdomain
dns_info() {
    local domain=$1
    local subdomain=$2
    ip=$(dig "$subdomain"."$domain" | grep -A1 'ANSWER SECTION:' | awk 'NR == 2 {print $5}')
    rec_type=$(dig "$subdomain"."$domain" | grep -A1 'ANSWER SECTION:' | awk 'NR == 2 {print $4}')
    echo "The subdomain $subdomain is a $rec_type record and points to $ip."
}

# Check if both domain and subdomain parameters are provided
if [ $# -eq 2 ]; then
    dns_info "$1" "$2"
else
    # Display information for default subdomains in the specified order
    dns_info "$1" "www"
    dns_info "$1" "lb-01"
    dns_info "$1" "web-01"
    dns_info "$1" "web-02"
fi
