#!/usr/bin/env bash
# Function to display DNS information for a subdomain
display_dns_info() {
    local domain="$1"
    local subdomain="$2"

# Query DNS records for the specified subdomain and domain
    dns_output=$(dig +short "$subdomain.$domain")

# Display the DNS information
     # Check if DNS output is empty (subdomain doesn't exist)
    if [ -z "$dns_output" ]; then
        echo "The subdomain '$subdomain' does not exist."
    else
        # Extract and display DNS record type and IP address
        rec_type=$(dig "$subdomain.$domain" | grep -A1 'ANSWER SECTION:' | awk 'NR == 2 {print $4}')
        ip=$(dig "$subdomain.$domain" | grep -A1 'ANSWER SECTION:' | awk 'NR == 2 {print $5}')
        echo "The subdomain $subdomain is a $rec_type record and points to $ip."
    fi
}

# Check if both domain and subdomain parameters are provided
if [ $# -eq 2 ]; then
    display_dns_info "$1" "$2"
else
    # Display information for default subdomains in the specified order
    display_dns_info "$1" "www"
    display_dns_info "$1" "lb-01"
    display_dns_info "$1" "web-01"
    display_dns_info "$1" "web-02"
fi
