#!/usr/bin/env bash
# Update the package list and install HAProxy
sudo apt-get -y update
sudo apt-get -y install haproxy

# Configure HAProxy
lines="\nfrontend frontend_server\n\tbind *:80\n\tdefault_backend backend_server\n\nbackend backend_server\n\tbalance roundrobin\n\tserver 251811-web-01 100.26.157.101:80 check\n\tserver 251811-web-02 54.157.150.183:80 check"

# Configure HAProxy init script
echo -e "$lines" | sudo tee /etc/haproxy/haproxy.cfg > /dev/null

# Restart HAProxy
sudo service haproxy restart
