#!/usr/bin/env bash
# Debugging Ubuntu container’s Nginx installation from listening on port 80
sed -i 's/[0-9]+ default_server/80 default_server/' /etc/nginx/sites-enabled/default
service nginx restart
