#!/usr/bin/env bash
# This script displays the content of the file /etc/passwd.
# The script should only display the username, user id and
# Home directory path for the user
while IFS=':' read -r username _ uid _ home _; do
	echo "$username:$uid:$home"
done < /etc/passwd
