#!/usr/bin/env bash
# This script displays the content of the file /etc/passwd
# using while loop + IFS
IFS=':'
while read -r username _ uid gid user_info home shell; do
	echo "The user $username is part of the $gid gang, lives in $home and rides $shell. $uid's place is protected by the passcode x, more info about the user here: $user_info"
done < /etc/passwd
