#!/usr/bin/env bash
# Displays Best School *10, but the 9th iteration displays
# Best School and then Hi on a new line
m=0
while [ $m -le 10 ]
do
	if [ $m -eq 9 ]; then
		echo "Hi"
	else
		echo "Best School"
	fi
	m=$((m + 1))
done
