#!/usr/bin/env bash
# This script displays:
# The content of the current dir in a list format
# Where only the part of the name after the first dash is displayed
for file in *
do
	echo "${file#*-}"
done
